name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # echo the current date
      - name: Echo the current date
        run: echo "The current date is $(date)"

      # - name: Checkout repository
      #   uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build and push Docker image
      #   run: |
      #     docker build -t my-dockerhub-username/my-app:latest .
      #     docker push my-dockerhub-username/my-app:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Update Kubernetes manifests with new image
  #       run: |
  #         cd manifests
  #         kustomize edit set image my-dockerhub-username/my-app=my-dockerhub-username/my-app:latest
  #         git config --global user.email "github-actions[bot]@users.noreply.github.com"
  #         git config --global user.name "GitHub Actions Bot"
  #         git add .
  #         git commit -m "Update image version to latest"
  #         git push

  #     - name: Deploy to ArgoCD
  #       run: |
  #         argocd app sync my-app
